builder = "NIXPACKS"

[deploy]
startCommand = "node src/bot.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"